stages:
  - test

##############################################################################
#                                 Test stage                                 #
##############################################################################

test_flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8

unit_test:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest


##############################################################################
#                              Build stage                                   #
##############################################################################