stages:
  - test
  - build

##############################################################################
#                                 Test stage                                 #
##############################################################################

test_flake8:
  image: ejplatform/python:alpine
  stage: test
  script:
    - flake8

unit_test:
  image: python:3.6
  stage: test
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest


##############################################################################
#                              Build stage                                   #
##############################################################################

build_joke:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  beforre_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t joke_haha:$ENV_TAG
  only:
    - /devel/
  environment: homolog

push_joke:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  beforre_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - docker build -t joke_haha:$ENV_TAG
    - docker push $DOCKER_USER/joke_haha:$ENV_TAG
  only:
    - /master/
  environment: production