version: "3"
services:
  jokes-haha:
    build:
      context: .
      dockerfile: ./Dockerfile

    ports:
      - 3000:5000

    volumes:
      - ./:/app

    depends_on:
     - mongo-db
  
  mongo-db:
    image: mongo:latest
    ports:
      - 27017:27017
    
    volumes:
      - /data/db:/data/db